# Generated by Django 3.2.5 on 2021-09-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0004_carowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='carlisting.carowner'),
        ),
    ]
