# Generated by Django 3.2.5 on 2021-09-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0005_car_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='contact_info',
            field=models.CharField(default='+254 720 111 111', help_text='Enter the car owners phone number starting with +254', max_length=20, verbose_name='Phone No: '),
            preserve_default=False,
        ),
    ]
