# Generated by Django 3.2.5 on 2021-09-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0006_carowner_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
