# Generated by Django 3.2.5 on 2021-09-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carlisting', '0007_car_car_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_images',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
